@startuml
'https://plantuml.com/class-diagram


class BaseEntity {
- id : String
}

class PhoneNumber {
- prefix : int
- number : String
}

class EmailAddress {
- localPart : String
- domain : String
}

class Contact {
- phone : PhoneNumber
- email : EmailAddress
}

class Address {
- street : String
- city : String
- postalCode : String
- country : String
}

class Username {
- firstName : String
- lastName : String
}

entity Customer extends BaseEntity {
- username : Username
- birthDate : LocalDate
- contact : Contact
- address : Address
+ updateContact(Contact) : Customer
+ updateAddress(Address) : Customer
}

entity Product extends BaseEntity {
- name : String
- description : String
- price : Money
- stock : int
}

enum PaymentStatus {
SUBMITTED
PROCESSING
COMPLETED
}

enum PaymentMethod {
VISA
MASTERCARD
PAYPAL
}

entity Payment extends BaseEntity {
- paymentMethod : PaymentMethod
- totalAmount : Money
- status : PaymentStatus
+ void setStatus(PaymentStatus)
+ void setCompletedAt(Date)
}


entity Shipment extends BaseEntity {
- username : Username
- contact : Contact
- address : Address
+ void setCompletedAt(Date)
}

entity CartLineItem extends BaseEntity {
- product : Product
+ void increaseQuantity(quantity : int)
+ Money unitPrice(currency : CurrencyUnit)
+ Money subtotal(currency : CurrencyUnit)
}

entity Cart extends BaseEntity {
- customerId : BaseEntity
- cartLineItems : Hashmap<String, CartLineItem>
- totalAmount : Money
+ void changeCurrency(currency : CurrencyUnit))
+ void addLineItemOrIncreaseLineItemQuantity(product : Product, quantity : int)
+ void replaceLineItem(product : Product, quantity : int)
}

enum OrderStatus {
SUBMITTED
PROCESSING
COMPLETED
}

entity Order extends BaseEntity {
- status : OrderStatus
+ void setStatus(OrderStatus)
+ void setCompletedAt(Date)
}

CartLineItem --> "1" Product
Cart "1" *-- "many" CartLineItem : contains
Customer *-- Cart
OrderStatus *-- Order : use
PaymentStatus *-- Payment : use
PaymentMethod *-- Payment : use
Contact -- PhoneNumber
Contact -- EmailAddress
Customer -- Contact
Customer -- Username
Customer -- Address
Shipment -- Contact
Shipment -- Username
Shipment -- Address

@enduml